# Generated by Django 5.0.2 on 2024-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='tickets_tutor', to='tickets.ticket'),
        ),
    ]
