# Generated by Django 5.0.2 on 2024-03-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_tutor_tickets'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_subject', to='tickets.organization'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tutors',
            field=models.ManyToManyField(related_name='tutors_subject', to='Users.tutor'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_ticket', to='Users.student'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_ticket', to='tickets.subject'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_ticket', to='Users.tutor'),
        ),
    ]
